### ISSUE TITLE
your code has a problem

### ISSUE THREAD

**Issue by ManH170** [ComboMC/Combo-Minecraft-Checker#1]
File "C:\Users\ducha\OneDrive\Desktop\Combo Minecraft Checker\main.py", line 5, in <module>
    import requests, os, threading, sys, time, random, ctypes, webbrowser,re, hashlib, datetime, os.path, tkinter
ModuleNotFoundError: No module named 'requests'

**Comment by EclipsesDev** [comment]
Sorry but the code haven't been update in a years now
